name: MonumentaNetworkChat
main: com.playmonumenta.networkchat.NetworkChatPlugin
version: 0.0.1
api-version: 1.13
depend: [CommandAPI,MonumentaNetworkRelay,MonumentaRedisSync,PlaceholderAPI]
softdepend: []
commands:
