name: MonumentaNetworkChat
main: com.playmonumenta.networkchat.NetworkChatPlugin
version: 1.4.2
api-version: 1.13
depend: [CommandAPI,MonumentaNetworkRelay,MonumentaRedisSync,PlaceholderAPI,ProtocolLib]
softdepend: []
commands:
